version: "3.8"

services:
  airlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: karunamay4055/airlink:0.0.2-local-prod
    networks:
      - airlink_internal
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .prod.env
    environment:
      PRIVATE_KEY_SYSTEM_PATH: /run/secrets/private_key.pem
      PUBLIC_KEY_SYSTEM_PATH: /run/secrets/public_key.pem
    secrets:
      - private_key.pem
      - public_key.pem

networks:
  airlink_internal:
    name: airlink
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

secrets:
  private_key.pem:
    file: /etc/secrets/private_key.pem
  public_key.pem:
    file: /etc/secrets/public_key.pem