version: "3.8"

services:
  airlink:
    build:
      context: .
      dockerfile: Dockerfile
    image: karunamay4055/airlink:prod
    networks:
      - airlink_internal
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .prod.env
    secrets:
      - private_key.pem
      - public_key.pem

networks:
  airlink_internal:
    name: airlink
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

secrets:
  private_key.pem:
    file: /etc/secrets/private_key.pem
  public_key.pem:
    file: /etc/secrets/public_key.pem